security:
    encoders:
        App\Entity\User:
            algorithm:          bcrypt

    providers:
        app_user_provider:
            entity:
                class:          App\Entity\User
                property:       email
    firewalls:
        dev:
            pattern:            ^/(_(profiler|wdt)|css|images|js)/
            security:           false
        main:
            anonymous:          true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:           app_logout
                target:         app_homepage

            remember_me:
                secret:         '%kernel.secret%'
                lifetime:       604800 # 1 week in seconds
                path:           /


    # Note:                     Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles:    ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
